[package]
name = "crane"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = {version = "4.5.32", features = ["derive"]}
colored = "3.0.0"

crane-core = { path = "../crane-core" }


[[bin]]
name = "llmbench"
path = "src/demos/llmbench/main.rs"

[[bin]]
name = "sparktts"
path = "src/demos/sparktts/main.rs"

[[bin]]
name = "qwenchat"
path = "src/demos/qwenchat/main.rs"

[[bin]]
name = "example"
path = "src/demos/example/main.rs"



[[bin]]
name = "moonshine_asr"
path = "src/demos/moonshine_asr.rs"