[package]
name = "crane"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = {version = "4.5.32", features = ["derive"]}
colored = "3.0.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "2.0"

crane-core = { path = "../crane-core" }
ribo = "0.1.3"
tokenizers = "0.22.2"

[features]
onnx = ["crane-core/onnx"]

[lib]
name = "crane"
path = "src/lib.rs"
