

[dependencies]
anyhow = "1.0.97"
clap = {version = "4.5.32", features = ["derive"]}
colored = "3.0.0"

crane-core = { path = "../crane-core" }
crane = {path = "../crane"}


[[bin]]
name = "test"
path = "src/test.rs"

